spring.application.name=github-data-service
spring.config.import=optional:secret.properties

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/github_data_db
spring.datasource.username=postgres
spring.jpa.datasource.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

github.api.base-url=https://api.github.com

github.repository.owner=chromium
github.repository.name=chromium
github.repository.start-date=2026-07-01T00:00:00Z

github.sync.per-page=100
github.sync.max-pages-per-run=5
github.sync.interval-ms=3600000
github.sync.initial-delay-ms=5000
github.sync.enabled=true
github.sync.seed-enabled=true